package surveyor.id.com.mobilesurvey.util;

import android.content.Context;
import android.util.Log;

import surveyor.id.com.mobilesurvey.modal.DatabaseManager;

/**
 * Created by 001810240 on 2/24/2020.
 */

public class DataSource {
    private final Context context;
    private DatabaseManager dm;

    public DataSource(Context context){
        this.context = context;
        dm = new DatabaseManager(context);
    }
    public void insertProv(){
        int provCount = dm.rowCountProvinsi();

        if (provCount < 1) {
            try {
                dm.addRowProvinsi("Sumatera Barat","13");
                dm.addRowProvinsi("Riau","14");
                dm.addRowProvinsi("Jambi","15");
                dm.addRowProvinsi("Sumatera Selatan","16");
                dm.addRowProvinsi("Bengkulu","17");
                dm.addRowProvinsi("Lampung","18");
                dm.addRowProvinsi("Kepulauan Bangka Belitung","19");
                dm.addRowProvinsi("Kepulauan Riau","21");
                dm.addRowProvinsi("Dki Jakarta","31");
                dm.addRowProvinsi("Jawa Barat","32");
                dm.addRowProvinsi("Jawa Tengah","33");
                dm.addRowProvinsi("Di Yogyakarta","34");
                dm.addRowProvinsi("Jawa Timur","35");
                dm.addRowProvinsi("Banten","36");
                dm.addRowProvinsi("Bali","51");
                dm.addRowProvinsi("Nusa Tenggara Barat","52");
                dm.addRowProvinsi("Nusa Tenggara Timur","53");
                dm.addRowProvinsi("Kalimantan Barat","61");
                dm.addRowProvinsi("Kalimantan Tengah","62");
                dm.addRowProvinsi("Kalimantan Selatan","63");
                dm.addRowProvinsi("Kalimantan Timur","64");
                dm.addRowProvinsi("Kalimantan Utara","65");
                dm.addRowProvinsi("Sulawesi Utara","71");
                dm.addRowProvinsi("Sulawesi Tengah","72");
                dm.addRowProvinsi("Sulawesi Selatan","73");
                dm.addRowProvinsi("Sulawesi Tenggara","74");
                dm.addRowProvinsi("Gorontalo","75");
                dm.addRowProvinsi("Sulawesi Barat","76");
                dm.addRowProvinsi("Maluku","81");
                dm.addRowProvinsi("Maluku Utara","82");
                dm.addRowProvinsi("Papua Barat","91");
                dm.addRowProvinsi("Papua","94");
                dm.addRowProvinsi("Aceh","11");
                dm.addRowProvinsi("Sumatera Utara","12");
            }catch (Exception e){
                e.printStackTrace();
                Log.e("ErrorInsert RowProvinsi",e.toString());
            }

        }
    }
    public void insertKota(){
        int kotaCount = dm.rowCountKota();

        if (kotaCount < 1){
            try {
                dm.addRowKota("Kab Aceh Tenggara","11","1104");
                dm.addRowKota("Kab Aceh Timur","11","1105");
                dm.addRowKota("Kab Aceh Tengah","11","1106");
                dm.addRowKota("Kab Aceh Barat","11","1107");
                dm.addRowKota("Kab Aceh Besar","11","1108");
                dm.addRowKota("Kab Pidie","11","1109");
                dm.addRowKota("Kab Bireuen","11","1110");
                dm.addRowKota("Kab Aceh Utara","11","1111");
                dm.addRowKota("Kab Aceh Barat Daya","11","1112");
                dm.addRowKota("Kab Gayo Lues","11","1113");
                dm.addRowKota("Kab Aceh Tamiang","11","1114");
                dm.addRowKota("Kab Nagan Raya","11","1115");
                dm.addRowKota("Kab Aceh Jaya","11","1116");
                dm.addRowKota("Kab Bener Meriah","11","1117");
                dm.addRowKota("Kab Pidie Jaya","11","1118");
                dm.addRowKota("KotaBanda Aceh","11","1171");
                dm.addRowKota("KotaSabang","11","1172");
                dm.addRowKota("KotaLangsa","11","1173");
                dm.addRowKota("KotaLhokseumawe","11","1174");
                dm.addRowKota("KotaSubulussalam","11","1175");
                dm.addRowKota("Kab Nias","12","1201");
                dm.addRowKota("Kab Mandailing Natal","12","1202");
                dm.addRowKota("Kab Tapanuli Selatan","12","1203");
                dm.addRowKota("Kab Tapanuli Tengah","12","1204");
                dm.addRowKota("Kab Tapanuli Utara","12","1205");
                dm.addRowKota("Kab Toba Samosir","12","1206");
                dm.addRowKota("Kab Labuhan Batu","12","1207");
                dm.addRowKota("Kab Asahan","12","1208");
                dm.addRowKota("Kab Simalungun","12","1209");
                dm.addRowKota("Kab Dairi","12","1210");
                dm.addRowKota("Kab Karo","12","1211");
                dm.addRowKota("Kab Deli Serdang","12","1212");
                dm.addRowKota("Kab Langkat","12","1213");
                dm.addRowKota("Kab Nias Selatan","12","1214");
                dm.addRowKota("Kab Humbang Hasundutan","12","1215");
                dm.addRowKota("Kab Pakpak Bharat","12","1216");
                dm.addRowKota("Kab Samosir","12","1217");
                dm.addRowKota("Kab Serdang Bedagai","12","1218");
                dm.addRowKota("Kab Batu Bara","12","1219");
                dm.addRowKota("Kab Padang Lawas Utara","12","1220");
                dm.addRowKota("Kab Padang Lawas","12","1221");
                dm.addRowKota("Kab Labuhan Batu Selatan","12","1222");
                dm.addRowKota("Kab Labuhan Batu Utara","12","1223");
                dm.addRowKota("Kab Nias Utara","12","1224");
                dm.addRowKota("Kab Nias Barat","12","1225");
                dm.addRowKota("KotaSibolga","12","1271");
                dm.addRowKota("KotaTanjung Balai","12","1272");
                dm.addRowKota("KotaPematang Siantar","12","1273");
                dm.addRowKota("KotaTebing Tinggi","12","1274");
                dm.addRowKota("KotaMedan","12","1275");
                dm.addRowKota("KotaBinjai","12","1276");
                dm.addRowKota("KotaPadangsidimpuan","12","1277");
                dm.addRowKota("KotaGunungsitoli","12","1278");
                dm.addRowKota("Kab Kepulauan Mentawai","13","1301");
                dm.addRowKota("Kab Pesisir Selatan","13","1302");
                dm.addRowKota("Kab Solok","13","1303");
                dm.addRowKota("Kab Sijunjung","13","1304");
                dm.addRowKota("Kab Tanah Datar","13","1305");
                dm.addRowKota("Kab Padang Pariaman","13","1306");
                dm.addRowKota("Kab Agam","13","1307");
                dm.addRowKota("Kab Lima Puluh Kota","13","1308");
                dm.addRowKota("Kab Pasaman","13","1309");
                dm.addRowKota("Kab Solok Selatan","13","1310");
                dm.addRowKota("Kab Dharmasraya","13","1311");
                dm.addRowKota("Kab Pasaman Barat","13","1312");
                dm.addRowKota("KotaPadang","13","1371");
                dm.addRowKota("KotaSolok","13","1372");
                dm.addRowKota("KotaSawah Lunto","13","1373");
                dm.addRowKota("KotaPadang Panjang","13","1374");
                dm.addRowKota("KotaBukittinggi","13","1375");
                dm.addRowKota("KotaPayakumbuh","13","1376");
                dm.addRowKota("KotaPariaman","13","1377");
                dm.addRowKota("Kab Kuantan Singingi","14","1401");
                dm.addRowKota("Kab Indragiri Hulu","14","1402");
                dm.addRowKota("Kab Indragiri Hilir","14","1403");
                dm.addRowKota("Kab Pelalawan","14","1404");
                dm.addRowKota("Kab S I A K","14","1405");
                dm.addRowKota("Kab Kampar","14","1406");
                dm.addRowKota("Kab Rokan Hulu","14","1407");
                dm.addRowKota("Kab Bengkalis","14","1408");
                dm.addRowKota("Kab Rokan Hilir","14","1409");
                dm.addRowKota("Kab Kepulauan Meranti","14","1410");
                dm.addRowKota("KotaPekanbaru","14","1471");
                dm.addRowKota("KotaD U M A I","14","1473");
                dm.addRowKota("Kab Kerinci","15","1501");
                dm.addRowKota("Kab Merangin","15","1502");
                dm.addRowKota("Kab Sarolangun","15","1503");
                dm.addRowKota("Kab Batang Hari","15","1504");
                dm.addRowKota("Kab Muaro Jambi","15","1505");
                dm.addRowKota("Kab Tanjung Jabung Timur","15","1506");
                dm.addRowKota("Kab Tanjung Jabung Barat","15","1507");
                dm.addRowKota("Kab Tebo","15","1508");
                dm.addRowKota("Kab Bungo","15","1509");
                dm.addRowKota("KotaJambi","15","1571");
                dm.addRowKota("KotaSungai Penuh","15","1572");
                dm.addRowKota("Kab Ogan Komering Ulu","16","1601");
                dm.addRowKota("Kab Ogan Komering Ilir","16","1602");
                dm.addRowKota("Kab Muara Enim","16","1603");
                dm.addRowKota("Kab Lahat","16","1604");
                dm.addRowKota("Kab Musi Rawas","16","1605");
                dm.addRowKota("Kab Musi Banyuasin","16","1606");
                dm.addRowKota("Kab Banyu Asin","16","1607");
                dm.addRowKota("Kab Ogan Komering Ulu Selatan","16","1608");
                dm.addRowKota("Kab Ogan Komering Ulu Timur","16","1609");
                dm.addRowKota("Kab Ogan Ilir","16","1610");
                dm.addRowKota("Kab Empat Lawang","16","1611");
                dm.addRowKota("KotaPalembang","16","1671");
                dm.addRowKota("KotaPrabumulih","16","1672");
                dm.addRowKota("KotaPagar Alam","16","1673");
                dm.addRowKota("KotaLubuklinggau","16","1674");
                dm.addRowKota("Kab Bengkulu Selatan","17","1701");
                dm.addRowKota("Kab Rejang Lebong","17","1702");
                dm.addRowKota("Kab Bengkulu Utara","17","1703");
                dm.addRowKota("Kab Kaur","17","1704");
                dm.addRowKota("Kab Seluma","17","1705");
                dm.addRowKota("Kab Mukomuko","17","1706");
                dm.addRowKota("Kab Lebong","17","1707");
                dm.addRowKota("Kab Kepahiang","17","1708");
                dm.addRowKota("Kab Bengkulu Tengah","17","1709");
                dm.addRowKota("KotaBengkulu","17","1771");
                dm.addRowKota("Kab Lampung Barat","18","1801");
                dm.addRowKota("Kab Tanggamus","18","1802");
                dm.addRowKota("Kab Lampung Selatan","18","1803");
                dm.addRowKota("Kab Lampung Timur","18","1804");
                dm.addRowKota("Kab Lampung Tengah","18","1805");
                dm.addRowKota("Kab Lampung Utara","18","1806");
                dm.addRowKota("Kab Way Kanan","18","1807");
                dm.addRowKota("Kab Tulangbawang","18","1808");
                dm.addRowKota("Kab Pesawaran","18","1809");
                dm.addRowKota("Kab Pringsewu","18","1810");
                dm.addRowKota("Kab Mesuji","18","1811");
                dm.addRowKota("Kab Tulang Bawang Barat","18","1812");
                dm.addRowKota("Kab Pesisir Barat","18","1813");
                dm.addRowKota("KotaBandar Lampung","18","1871");
                dm.addRowKota("KotaMetro","18","1872");
                dm.addRowKota("Kab Bangka","19","1901");
                dm.addRowKota("Kab Belitung","19","1902");
                dm.addRowKota("Kab Bangka Barat","19","1903");
                dm.addRowKota("Kab Bangka Tengah","19","1904");
                dm.addRowKota("Kab Bangka Selatan","19","1905");
                dm.addRowKota("Kab Belitung Timur","19","1906");
                dm.addRowKota("Kab Simeulue","11","1101");
                dm.addRowKota("Kab Aceh Singkil","11","1102");
                dm.addRowKota("KotaPangkal Pinang","19","1971");
                dm.addRowKota("Kab Karimun","21","2101");
                dm.addRowKota("Kab Bintan","21","2102");
                dm.addRowKota("Kab Natuna","21","2103");
                dm.addRowKota("Kab Lingga","21","2104");
                dm.addRowKota("Kab Kepulauan Anambas","21","2105");
                dm.addRowKota("KotaB A T A M","21","2171");
                dm.addRowKota("KotaTanjung Pinang","21","2172");
                dm.addRowKota("Kab Kepulauan Seribu","31","3101");
                dm.addRowKota("Kota Jakarta Pusat","31","3171");
                dm.addRowKota("Kab Sragen","33","3314");
                dm.addRowKota("Kab Grobogan","33","3315");
                dm.addRowKota("Kab Blora","33","3316");
                dm.addRowKota("Kab Rembang","33","3317");
                dm.addRowKota("Kab Pati","33","3318");
                dm.addRowKota("Kab Kudus","33","3319");
                dm.addRowKota("Kab Jepara","33","3320");
                dm.addRowKota("Kab Demak","33","3321");
                dm.addRowKota("Kab Semarang","33","3322");
                dm.addRowKota("Kab Temanggung","33","3323");
                dm.addRowKota("Kab Kendal","33","3324");
                dm.addRowKota("Kab Batang","33","3325");
                dm.addRowKota("Kab Pekalongan","33","3326");
                dm.addRowKota("Kab Pemalang","33","3327");
                dm.addRowKota("Kab Tegal","33","3328");
                dm.addRowKota("Kab Brebes","33","3329");
                dm.addRowKota("KotaMagelang","33","3371");
                dm.addRowKota("KotaSurakarta","33","3372");
                dm.addRowKota("KotaSalatiga","33","3373");
                dm.addRowKota("KotaSemarang","33","3374");
                dm.addRowKota("KotaPekalongan","33","3375");
                dm.addRowKota("KotaTegal","33","3376");
                dm.addRowKota("Kab Kulon Progo","34","3401");
                dm.addRowKota("Kab Bantul","34","3402");
                dm.addRowKota("Kab Gunung Kidul","34","3403");
                dm.addRowKota("Kab Sleman","34","3404");
                dm.addRowKota("KotaYogyakarta","34","3471");
                dm.addRowKota("Kab Pacitan","35","3501");
                dm.addRowKota("Kab Ponorogo","35","3502");
                dm.addRowKota("Kab Trenggalek","35","3503");
                dm.addRowKota("Kab Tulungagung","35","3504");
                dm.addRowKota("Kab Blitar","35","3505");
                dm.addRowKota("Kab Kediri","35","3506");
                dm.addRowKota("Kab Malang","35","3507");
                dm.addRowKota("Kab Lumajang","35","3508");
                dm.addRowKota("Kab Jember","35","3509");
                dm.addRowKota("Kab Banyuwangi","35","3510");
                dm.addRowKota("Kab Bondowoso","35","3511");
                dm.addRowKota("Kab Situbondo","35","3512");
                dm.addRowKota("Kab Probolinggo","35","3513");
                dm.addRowKota("Kab Pasuruan","35","3514");
                dm.addRowKota("Kab Sidoarjo","35","3515");
                dm.addRowKota("Kab Mojokerto","35","3516");
                dm.addRowKota("Kab Jombang","35","3517");
                dm.addRowKota("Kab Nganjuk","35","3518");
                dm.addRowKota("Kab Madiun","35","3519");
                dm.addRowKota("Kab Magetan","35","3520");
                dm.addRowKota("Kab Ngawi","35","3521");
                dm.addRowKota("Kab Bojonegoro","35","3522");
                dm.addRowKota("Kab Tuban","35","3523");
                dm.addRowKota("Kab Lamongan","35","3524");
                dm.addRowKota("Kab Gresik","35","3525");
                dm.addRowKota("Kab Bangkalan","35","3526");
                dm.addRowKota("Kab Sampang","35","3527");
                dm.addRowKota("Kab Pamekasan","35","3528");
                dm.addRowKota("Kab Sumenep","35","3529");
                dm.addRowKota("KotaKediri","35","3571");
                dm.addRowKota("KotaBlitar","35","3572");
                dm.addRowKota("KotaMalang","35","3573");
                dm.addRowKota("KotaProbolinggo","35","3574");
                dm.addRowKota("KotaPasuruan","35","3575");
                dm.addRowKota("KotaMojokerto","35","3576");
                dm.addRowKota("KotaMadiun","35","3577");
                dm.addRowKota("KotaSurabaya","35","3578");
                dm.addRowKota("KotaBatu","35","3579");
                dm.addRowKota("Kab Pandeglang","36","3601");
                dm.addRowKota("Kab Lebak","36","3602");
                dm.addRowKota("Kab Tangerang","36","3603");
                dm.addRowKota("Kab Serang","36","3604");
                dm.addRowKota("KotaTangerang","36","3671");
                dm.addRowKota("KotaCilegon","36","3672");
                dm.addRowKota("KotaSerang","36","3673");
                dm.addRowKota("KotaTangerang Selatan","36","3674");
                dm.addRowKota("Kab Jembrana","51","5101");
                dm.addRowKota("Kab Tabanan","51","5102");
                dm.addRowKota("Kab Badung","51","5103");
                dm.addRowKota("Kab Gianyar","51","5104");
                dm.addRowKota("Kab Klungkung","51","5105");
                dm.addRowKota("Kab Bangli","51","5106");
                dm.addRowKota("Kab Karang Asem","51","5107");
                dm.addRowKota("Kab Buleleng","51","5108");
                dm.addRowKota("KotaDenpasar","51","5171");
                dm.addRowKota("Kab Lombok Barat","52","5201");
                dm.addRowKota("Kab Lombok Tengah","52","5202");
                dm.addRowKota("Kab Lombok Timur","52","5203");
                dm.addRowKota("Kab Sumbawa","52","5204");
                dm.addRowKota("Kab Dompu","52","5205");
                dm.addRowKota("Kab Bima","52","5206");
                dm.addRowKota("Kab Sumbawa Barat","52","5207");
                dm.addRowKota("Kab Lombok Utara","52","5208");
                dm.addRowKota("KotaMataram","52","5271");
                dm.addRowKota("KotaBima","52","5272");
                dm.addRowKota("Kab Sumba Barat","53","5301");
                dm.addRowKota("Kab Sumba Timur","53","5302");
                dm.addRowKota("Kab Kupang","53","5303");
                dm.addRowKota("Kab Timor Tengah Selatan","53","5304");
                dm.addRowKota("Kab Timor Tengah Utara","53","5305");
                dm.addRowKota("Kab Belu","53","5306");
                dm.addRowKota("Kab Alor","53","5307");
                dm.addRowKota("Kab Lembata","53","5308");
                dm.addRowKota("Kab Flores Timur","53","5309");
                dm.addRowKota("Kab Sikka","53","5310");
                dm.addRowKota("Kab Ende","53","5311");
                dm.addRowKota("Kab Ngada","53","5312");
                dm.addRowKota("Kab Manggarai","53","5313");
                dm.addRowKota("Kab Rote Ndao","53","5314");
                dm.addRowKota("Kab Manggarai Barat","53","5315");
                dm.addRowKota("Kab Sumba Tengah","53","5316");
                dm.addRowKota("Kab Sumba Barat Daya","53","5317");
                dm.addRowKota("Kab Nagekeo","53","5318");
                dm.addRowKota("Kab Manggarai Timur","53","5319");
                dm.addRowKota("Kab Sabu Raijua","53","5320");
                dm.addRowKota("KotaKupang","53","5371");
                dm.addRowKota("Kab Sambas","61","6101");
                dm.addRowKota("Kab Bengkayang","61","6102");
                dm.addRowKota("Kab Landak","61","6103");
                dm.addRowKota("Kab Pontianak","61","6104");
                dm.addRowKota("Kab Sanggau","61","6105");
                dm.addRowKota("Kab Ketapang","61","6106");
                dm.addRowKota("Kab Sintang","61","6107");
                dm.addRowKota("Kab Kapuas Hulu","61","6108");
                dm.addRowKota("Kab Sekadau","61","6109");
                dm.addRowKota("Kab Melawi","61","6110");
                dm.addRowKota("Kab Kayong Utara","61","6111");
                dm.addRowKota("Kab Kubu Raya","61","6112");
                dm.addRowKota("KotaPontianak","61","6171");
                dm.addRowKota("KotaSingkawang","61","6172");
                dm.addRowKota("Kab Kotawaringin Barat","62","6201");
                dm.addRowKota("Kab Kotawaringin Timur","62","6202");
                dm.addRowKota("Kab Kapuas","62","6203");
                dm.addRowKota("Kab Barito Selatan","62","6204");
                dm.addRowKota("Kab Barito Utara","62","6205");
                dm.addRowKota("Kab Sukamara","62","6206");
                dm.addRowKota("Kab Lamandau","62","6207");
                dm.addRowKota("Kab Seruyan","62","6208");
                dm.addRowKota("Kab Katingan","62","6209");
                dm.addRowKota("Kab Pulang Pisau","62","6210");
                dm.addRowKota("Kab Gunung Mas","62","6211");
                dm.addRowKota("Kab Barito Timur","62","6212");
                dm.addRowKota("Kab Murung Raya","62","6213");
                dm.addRowKota("Kota Palangka Raya","62","6271");
                dm.addRowKota("Kab Tanah Laut","63","6301");
                dm.addRowKota("Kab Kota Baru","63","6302");
                dm.addRowKota("Kab Banjar","63","6303");
                dm.addRowKota("Kab Barito Kuala","63","6304");
                dm.addRowKota("Kab Tapin","63","6305");
                dm.addRowKota("Kab Hulu Sungai Selatan","63","6306");
                dm.addRowKota("Kab Hulu Sungai Tengah","63","6307");
                dm.addRowKota("Kab Hulu Sungai Utara","63","6308");
                dm.addRowKota("Kab Tabalong","63","6309");
                dm.addRowKota("Kab Tanah Bumbu","63","6310");
                dm.addRowKota("Kab Balangan","63","6311");
                dm.addRowKota("KotaBanjarmasin","63","6371");
                dm.addRowKota("KotaBanjar Baru","63","6372");
                dm.addRowKota("Kab Paser","64","6401");
                dm.addRowKota("Kab Kutai Barat","64","6402");
                dm.addRowKota("Kab Kutai Kartanegara","64","6403");
                dm.addRowKota("Kab Kutai Timur","64","6404");
                dm.addRowKota("Kab Berau","64","6405");
                dm.addRowKota("Kota Bekasi","32","3275");
                dm.addRowKota("KotaDepok","32","3276");
                dm.addRowKota("Kab Aceh Selatan","11","1103");
                dm.addRowKota("Kota Jakarta Utara","31","3172");
                dm.addRowKota("Kota Jakarta Barat","31","3173");
                dm.addRowKota("Kota Jakarta Selatan","31","3174");
                dm.addRowKota("Kota Jakarta Timur","31","3175");
                dm.addRowKota("Kab Bogor","32","3201");
                dm.addRowKota("Kab Sukabumi","32","3202");
                dm.addRowKota("Kab Cianjur","32","3203");
                dm.addRowKota("Kab Bandung","32","3204");
                dm.addRowKota("Kab Garut","32","3205");
                dm.addRowKota("Kab Tasikmalaya","32","3206");
                dm.addRowKota("Kab Ciamis","32","3207");
                dm.addRowKota("Kab Kuningan","32","3208");
                dm.addRowKota("Kab Cirebon","32","3209");
                dm.addRowKota("Kab Majalengka","32","3210");
                dm.addRowKota("Kab Sumedang","32","3211");
                dm.addRowKota("Kab Indramayu","32","3212");
                dm.addRowKota("Kab Subang","32","3213");
                dm.addRowKota("Kab Purwakarta","32","3214");
                dm.addRowKota("Kab Karawang","32","3215");
                dm.addRowKota("Kab Bekasi","32","3216");
                dm.addRowKota("Kab Bandung Barat","32","3217");
                dm.addRowKota("Kab Pangandaran","32","3218");
                dm.addRowKota("KotaBogor","32","3271");
                dm.addRowKota("KotaSukabumi","32","3272");
                dm.addRowKota("KotaBandung","32","3273");
                dm.addRowKota("KotaCirebon","32","3274");
                dm.addRowKota("Kab Penajam Paser Utara","64","6409");
                dm.addRowKota("KotaBalikpapan","64","6471");
                dm.addRowKota("KotaSamarinda","64","6472");
                dm.addRowKota("KotaBontang","64","6474");
                dm.addRowKota("Kab Malinau","65","6501");
                dm.addRowKota("Kab Bulungan","65","6502");
                dm.addRowKota("Kab Tana Tidung","65","6503");
                dm.addRowKota("Kab Nunukan","65","6504");
                dm.addRowKota("KotaTarakan","65","6571");
                dm.addRowKota("Kab Bolaang Mongondow","71","7101");
                dm.addRowKota("Kab Minahasa","71","7102");
                dm.addRowKota("Kab Kepulauan Sangihe","71","7103");
                dm.addRowKota("Kab Kepulauan Talaud","71","7104");
                dm.addRowKota("Kab Minahasa Selatan","71","7105");
                dm.addRowKota("Kab Minahasa Utara","71","7106");
                dm.addRowKota("Kab Bolaang Mongondow Utara","71","7107");
                dm.addRowKota("Kab Siau Tagulandang Biaro","71","7108");
                dm.addRowKota("Kab Minahasa Tenggara","71","7109");
                dm.addRowKota("Kab Bolaang Mongondow Selatan","71","7110");
                dm.addRowKota("Kab Bolaang Mongondow Timur","71","7111");
                dm.addRowKota("KotaManado","71","7171");
                dm.addRowKota("KotaBitung","71","7172");
                dm.addRowKota("KotaTomohon","71","7173");
                dm.addRowKota("KotaKotamobagu","71","7174");
                dm.addRowKota("Kab Banggai Kepulauan","72","7201");
                dm.addRowKota("Kab Banggai","72","7202");
                dm.addRowKota("Kab Morowali","72","7203");
                dm.addRowKota("Kab Poso","72","7204");
                dm.addRowKota("Kab Donggala","72","7205");
                dm.addRowKota("Kab Toli-toli","72","7206");
                dm.addRowKota("Kab Buol","72","7207");
                dm.addRowKota("Kab Parigi Moutong","72","7208");
                dm.addRowKota("Kab Tojo Una-una","72","7209");
                dm.addRowKota("Kab Sigi","72","7210");
                dm.addRowKota("KotaPalu","72","7271");
                dm.addRowKota("Kab Kepulauan Selayar","73","7301");
                dm.addRowKota("Kab Bulukumba","73","7302");
                dm.addRowKota("Kab Bantaeng","73","7303");
                dm.addRowKota("Kab Jeneponto","73","7304");
                dm.addRowKota("Kab Takalar","73","7305");
                dm.addRowKota("Kab Gowa","73","7306");
                dm.addRowKota("Kab Sinjai","73","7307");
                dm.addRowKota("Kab Maros","73","7308");
                dm.addRowKota("Kab Pangkajene Dan Kepulauan","73","7309");
                dm.addRowKota("Kab Barru","73","7310");
                dm.addRowKota("Kab Bone","73","7311");
                dm.addRowKota("Kab Soppeng","73","7312");
                dm.addRowKota("Kab Wajo","73","7313");
                dm.addRowKota("Kab Sidenreng Rappang","73","7314");
                dm.addRowKota("Kab Pinrang","73","7315");
                dm.addRowKota("Kab Enrekang","73","7316");
                dm.addRowKota("Kab Luwu","73","7317");
                dm.addRowKota("Kab Tana Toraja","73","7318");
                dm.addRowKota("Kab Luwu Utara","73","7322");
                dm.addRowKota("Kab Luwu Timur","73","7325");
                dm.addRowKota("Kab Toraja Utara","73","7326");
                dm.addRowKota("KotaMakassar","73","7371");
                dm.addRowKota("KotaParepare","73","7372");
                dm.addRowKota("KotaPalopo","73","7373");
                dm.addRowKota("Kab Buton","74","7401");
                dm.addRowKota("Kab Muna","74","7402");
                dm.addRowKota("Kab Konawe","74","7403");
                dm.addRowKota("Kab Kolaka","74","7404");
                dm.addRowKota("Kab Konawe Selatan","74","7405");
                dm.addRowKota("Kab Bombana","74","7406");
                dm.addRowKota("Kab Wakatobi","74","7407");
                dm.addRowKota("Kab Kolaka Utara","74","7408");
                dm.addRowKota("Kab Buton Utara","74","7409");
                dm.addRowKota("Kab Konawe Utara","74","7410");
                dm.addRowKota("KotaKendari","74","7471");
                dm.addRowKota("KotaBaubau","74","7472");
                dm.addRowKota("Kab Boalemo","75","7501");
                dm.addRowKota("Kab Gorontalo","75","7502");
                dm.addRowKota("Kab Pohuwato","75","7503");
                dm.addRowKota("Kab Bone Bolango","75","7504");
                dm.addRowKota("Kab Gorontalo Utara","75","7505");
                dm.addRowKota("KotaGorontalo","75","7571");
                dm.addRowKota("Kab Majene","76","7601");
                dm.addRowKota("Kab Polewali Mandar","76","7602");
                dm.addRowKota("Kab Mamasa","76","7603");
                dm.addRowKota("Kab Mamuju","76","7604");
                dm.addRowKota("Kab Mamuju Utara","76","7605");
                dm.addRowKota("Kab Maluku Tenggara Barat","81","8101");
                dm.addRowKota("Kab Maluku Tenggara","81","8102");
                dm.addRowKota("Kab Maluku Tengah","81","8103");
                dm.addRowKota("Kab Buru","81","8104");
                dm.addRowKota("Kab Kepulauan Aru","81","8105");
                dm.addRowKota("Kab Seram Bagian Barat","81","8106");
                dm.addRowKota("Kab Seram Bagian Timur","81","8107");
                dm.addRowKota("Kab Maluku Barat Daya","81","8108");
                dm.addRowKota("Kab Buru Selatan","81","8109");
                dm.addRowKota("KotaAmbon","81","8171");
                dm.addRowKota("KotaTual","81","8172");
                dm.addRowKota("Kab Halmahera Barat","82","8201");
                dm.addRowKota("Kab Halmahera Tengah","82","8202");
                dm.addRowKota("Kab Kepulauan Sula","82","8203");
                dm.addRowKota("Kab Halmahera Selatan","82","8204");
                dm.addRowKota("Kab Halmahera Utara","82","8205");
                dm.addRowKota("Kab Halmahera Timur","82","8206");
                dm.addRowKota("Kab Pulau Morotai","82","8207");
                dm.addRowKota("KotaTernate","82","8271");
                dm.addRowKota("KotaTidore Kepulauan","82","8272");
                dm.addRowKota("Kab Fakfak","91","9101");
                dm.addRowKota("Kab Kaimana","91","9102");
                dm.addRowKota("Kab Teluk Wondama","91","9103");
                dm.addRowKota("Kab Teluk Bintuni","91","9104");
                dm.addRowKota("Kab Manokwari","91","9105");
                dm.addRowKota("Kab Sorong Selatan","91","9106");
                dm.addRowKota("Kab Sorong","91","9107");
                dm.addRowKota("Kab Raja Ampat","91","9108");
                dm.addRowKota("Kab Tambrauw","91","9109");
                dm.addRowKota("Kab Maybrat","91","9110");
                dm.addRowKota("KotaSorong","91","9171");
                dm.addRowKota("Kab Merauke","94","9401");
                dm.addRowKota("Kab Jayawijaya","94","9402");
                dm.addRowKota("Kab Jayapura","94","9403");
                dm.addRowKota("Kab Nabire","94","9404");
                dm.addRowKota("Kab Kepulauan Yapen","94","9408");
                dm.addRowKota("Kab Biak Numfor","94","9409");
                dm.addRowKota("Kab Paniai","94","9410");
                dm.addRowKota("Kab Puncak Jaya","94","9411");
                dm.addRowKota("Kab Mimika","94","9412");
                dm.addRowKota("Kab Boven Digoel","94","9413");
                dm.addRowKota("Kab Mappi","94","9414");
                dm.addRowKota("Kab Asmat","94","9415");
                dm.addRowKota("Kab Yahukimo","94","9416");
                dm.addRowKota("Kab Pegunungan Bintang","94","9417");
                dm.addRowKota("Kab Tolikara","94","9418");
                dm.addRowKota("Kab Sarmi","94","9419");
                dm.addRowKota("Kab Keerom","94","9420");
                dm.addRowKota("Kab Waropen","94","9426");
                dm.addRowKota("Kab Supiori","94","9427");
                dm.addRowKota("Kab Mamberamo Raya","94","9428");
                dm.addRowKota("Kab Nduga","94","9429");
                dm.addRowKota("Kab Lanny Jaya","94","9430");
                dm.addRowKota("Kab Mamberamo Tengah","94","9431");
                dm.addRowKota("Kab Yalimo","94","9432");
                dm.addRowKota("Kab Puncak","94","9433");
                dm.addRowKota("Kab Dogiyai","94","9434");
                dm.addRowKota("Kab Intan Jaya","94","9435");
                dm.addRowKota("Kab Deiyai","94","9436");
                dm.addRowKota("KotaJayapura","94","9471");
                dm.addRowKota("KotaCimahi","32","3277");
                dm.addRowKota("KotaTasikmalaya","32","3278");
                dm.addRowKota("KotaBanjar","32","3279");
                dm.addRowKota("Kab Cilacap","33","3301");
                dm.addRowKota("Kab Banyumas","33","3302");
                dm.addRowKota("Kab Purbalingga","33","3303");
                dm.addRowKota("Kab Banjarnegara","33","3304");
                dm.addRowKota("Kab Kebumen","33","3305");
                dm.addRowKota("Kab Purworejo","33","3306");
                dm.addRowKota("Kab Wonosobo","33","3307");
                dm.addRowKota("Kab Magelang","33","3308");
                dm.addRowKota("Kab Boyolali","33","3309");
                dm.addRowKota("Kab Klaten","33","3310");
                dm.addRowKota("Kab Sukoharjo","33","3311");
                dm.addRowKota("Kab Wonogiri","33","3312");
                dm.addRowKota("Kab Karanganyar","33","3313");
            }catch (Exception e){
                e.printStackTrace();
                Log.e("ErrorInsert RowKota",e.toString());
            }
        }
    }
}
